FROM ubuntu:latest

RUN apt-get update 
RUN apt-get install openssl

# Cleanup
RUN rm -rf /var/lib/apt/lists/*
 
WORKDIR /opt/pfx

ARG LOCAL_PFX_FOLDER=./certificates
COPY $LOCAL_PFX_FOLDER ./

ENTRYPOINT [ "/bin/bash" ]
